CREATE TYPE "public"."bug_severity" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');--> statement-breakpoint
CREATE TYPE "public"."bug_status" AS ENUM('SUBMITTED', 'PROCESSING', 'ACCEPTED', 'REJECTED');--> statement-breakpoint
CREATE TYPE "public"."bug_tag" AS ENUM('UI', 'FUNCTIONALITY', 'PERFORMANCE', 'SECURITY', 'CRASH', 'NETWORK', 'DATABASE', 'OTHER');--> statement-breakpoint
CREATE TABLE "personal-bug-list_applications" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(50) NOT NULL,
	"key" text NOT NULL,
	"secret" text NOT NULL,
	"is_revoked" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "application_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "personal-bug-list_bug_images" (
	"id" uuid PRIMARY KEY NOT NULL,
	"bug_id" uuid NOT NULL,
	"file" varchar(256) NOT NULL,
	"file_name" varchar(256) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "personal-bug-list_bugs" (
	"id" uuid PRIMARY KEY NOT NULL,
	"app_id" uuid NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"severity" "bug_severity" NOT NULL,
	"tags" "bug_tag" NOT NULL,
	"status" "bug_status" DEFAULT 'SUBMITTED' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "personal-bug-list_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "personal-bug-list_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "post_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "personal-bug-list_users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"username" varchar(50) NOT NULL,
	"password" varchar(150) NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "personal-bug-list_bug_images" ADD CONSTRAINT "personal-bug-list_bug_images_bug_id_personal-bug-list_bugs_id_fk" FOREIGN KEY ("bug_id") REFERENCES "public"."personal-bug-list_bugs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal-bug-list_bugs" ADD CONSTRAINT "personal-bug-list_bugs_app_id_personal-bug-list_applications_id_fk" FOREIGN KEY ("app_id") REFERENCES "public"."personal-bug-list_applications"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "application_key_idx" ON "personal-bug-list_applications" USING btree ("key");--> statement-breakpoint
CREATE INDEX "application_idx" ON "personal-bug-list_applications" USING btree ("id");--> statement-breakpoint
CREATE INDEX "bug_image_id_idx" ON "personal-bug-list_bug_images" USING btree ("id");--> statement-breakpoint
CREATE INDEX "bug_image_bug_id_idx" ON "personal-bug-list_bug_images" USING btree ("bug_id");--> statement-breakpoint
CREATE INDEX "bug_image_created_at_idx" ON "personal-bug-list_bug_images" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "bug_id_idx" ON "personal-bug-list_bugs" USING btree ("id");--> statement-breakpoint
CREATE INDEX "bug_app_id_idx" ON "personal-bug-list_bugs" USING btree ("app_id");--> statement-breakpoint
CREATE INDEX "bug_title_idx" ON "personal-bug-list_bugs" USING btree ("title");--> statement-breakpoint
CREATE INDEX "bug_severity_idx" ON "personal-bug-list_bugs" USING btree ("severity");--> statement-breakpoint
CREATE INDEX "bug_tags_idx" ON "personal-bug-list_bugs" USING btree ("tags");--> statement-breakpoint
CREATE INDEX "bug_status_idx" ON "personal-bug-list_bugs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "bug_created_at_idx" ON "personal-bug-list_bugs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "post_name_idx" ON "personal-bug-list_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "username_idx" ON "personal-bug-list_users" USING btree ("username");--> statement-breakpoint
CREATE INDEX "user_idx" ON "personal-bug-list_users" USING btree ("id");